sudo: required
services:
  - docker

before_install:
  - docker build -t davidgallardo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidgallardo/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-833398140968"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"